title: Priyanka Singh

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: minimal light

# Links 
# If you don't need one of them, you may delete the corresponding line.
github_link: https://github.com/kumaripriyankasingh
linkedin: https://www.linkedin.com/in/kumari-priyanka-singh/

# Images (e.g., your profile picture and your website's favicon) 
avatar: ./assets/images/avatar.png

# Google Analytics ID
# Please remove this if you don't use Google Analytics
google_analytics: 

remote_theme: pages-themes/minimal@v0.2.0
